name: Flutter CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.dart

      - name: Debug changed files
        run: echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"

  analyzer:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}-pub

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze ${{ needs.changes.outputs.all_changed_files }}

  formatter:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}-pub

      - name: Get dependencies
        run: flutter pub get

      - name: Format code
        run: dart format -l 120 --set-exit-if-changed ${{ needs.changes.outputs.all_changed_files }}

  test_coverage:
    runs-on: ubuntu-latest
    needs: [analyzer, formatter]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29"

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-3.29-pub

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Check generated coverage report
        run: ls -lah coverage && cat coverage/lcov.info | head -n 20

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: coverage/lcov.info
