name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.dart

  analyzer:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29"
          channel: "stable"

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-3.29-pub

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze ${{ needs.changes.outputs.all_changed_files }}

  formatter:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29"
          channel: "stable"

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-3.29-pub

      - name: Get dependencies
        run: flutter pub get

      - name: Format code
        run: dart format -l 120 --set-exit-if-changed ${{ needs.changes.outputs.all_changed_files }}

      - name: Check if files are changed after formatting
        id: check-changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit and push changes
        if: steps.check-changes.outputs.stdout != ''
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-format code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_coverage:
    runs-on: ubuntu-latest
    needs: [analyzer, formatter]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29"
          channel: "stable"

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: flutter-${{ runner.os }}-3.29-pub

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Check generated coverage report
        run: ls -lah coverage && cat coverage/lcov.info | head -n 20

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: coverage/lcov.info
